services:
  swagger-editor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swagger-editor
    restart: on-failure
    networks:
      - cnaf-bridge-network
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - $API_VOLUME_MOUNT:/src/swagger/swagger.json
networks:
  cnaf-bridge-network:
    driver: bridge
