apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swagger-editor.fullname" . }}
  labels:
    {{- include "swagger-editor.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJET0NLRVJfVVNFUiIsInBhc3N3b3JkIjoiRE9DS0VSX1BBU1NXT1JEIiwiYXV0aCI6IlJFOURTMFZTWDFWVFJWSTZSRTlEUzBWU1gxQkJVMU5YVDFKRSJ9fX0=
