apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swagger-editor-app
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: 'swagger'
  source:
    path: 'swagger-editor'
    repoURL: 'https://github.com/digitastuces/swagger-editor.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
